<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

class ApiDocumentationController extends Controller
{
    public function index()
    {
        $modules = collect($this->getModules());

        return view('admin.api-documentation.index', compact('modules'));
    }

    private function getModules(): array
    {
        return [
            [
                'name' => 'Dashboard',
                'prefix' => 'dashboard',
                'color' => '#520A18',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'dashboard/stats', 'desc' => 'Summary statistics for all content (total banners, news, projects, etc.)'],
                    ['method' => 'GET', 'path' => 'dashboard/recent', 'desc' => 'List of recent activities/content for the dashboard'],
                ],
            ],
            [
                'name' => 'Banner',
                'prefix' => 'banner',
                'color' => '#68001C',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'banner', 'desc' => 'Display all banners'],
                    ['method' => 'POST', 'path' => 'banner', 'desc' => 'Create a new banner (upload image: gambar)'],
                    ['method' => 'GET', 'path' => 'banner/{id}', 'desc' => 'Banner detail by ID'],
                    ['method' => 'PUT', 'path' => 'banner/{id}', 'desc' => 'Update banner data'],
                    ['method' => 'PATCH', 'path' => 'banner/{id}/toggle-status', 'desc' => 'Enable / disable banner'],
                    ['method' => 'DELETE', 'path' => 'banner/{id}', 'desc' => 'Delete banner along with its image'],
                ],
            ],
            [
                'name' => 'Homepage',
                'prefix' => 'beranda',
                'color' => '#821E38',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'beranda', 'desc' => 'Display all homepage content'],
                    ['method' => 'POST', 'path' => 'beranda', 'desc' => 'Create new homepage content'],
                    ['method' => 'GET', 'path' => 'beranda/active', 'desc' => 'Homepage content with active status'],
                    ['method' => 'PUT', 'path' => 'beranda/update-urutan', 'desc' => 'Update homepage content display order'],
                    ['method' => 'GET', 'path' => 'beranda/section/{section}', 'desc' => 'Homepage content by section (about, structure, etc.)'],
                    ['method' => 'GET', 'path' => 'beranda/{id}', 'desc' => 'Homepage content detail by ID'],
                    ['method' => 'PUT', 'path' => 'beranda/{id}', 'desc' => 'Update homepage content'],
                    ['method' => 'PATCH', 'path' => 'beranda/{id}/toggle-status', 'desc' => 'Enable / disable homepage content'],
                    ['method' => 'DELETE', 'path' => 'beranda/{id}', 'desc' => 'Delete homepage content'],
                ],
            ],
            [
                'name' => 'About',
                'prefix' => 'tentang',
                'color' => '#132C5C',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'tentang', 'desc' => 'Display all about content'],
                    ['method' => 'POST', 'path' => 'tentang', 'desc' => 'Create new about content'],
                    ['method' => 'GET', 'path' => 'tentang/active', 'desc' => 'About content with active status'],
                    ['method' => 'PUT', 'path' => 'tentang/update-urutan', 'desc' => 'Update about content display order'],
                    ['method' => 'GET', 'path' => 'tentang/section/{section}', 'desc' => 'About content by section'],
                    ['method' => 'GET', 'path' => 'tentang/{id}', 'desc' => 'About content detail by ID'],
                    ['method' => 'PUT', 'path' => 'tentang/{id}', 'desc' => 'Update about content'],
                    ['method' => 'PATCH', 'path' => 'tentang/{id}/toggle-status', 'desc' => 'Enable / disable about content'],
                    ['method' => 'DELETE', 'path' => 'tentang/{id}', 'desc' => 'Delete about content'],
                ],
            ],
            [
                'name' => 'Partners',
                'prefix' => 'mitra',
                'color' => '#2B4E94',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'mitra', 'desc' => 'Display all partner data'],
                    ['method' => 'POST', 'path' => 'mitra', 'desc' => 'Create a new partner (upload logo)'],
                    ['method' => 'GET', 'path' => 'mitra/active', 'desc' => 'Partners with active status'],
                    ['method' => 'PUT', 'path' => 'mitra/update-urutan', 'desc' => 'Update partner display order'],
                    ['method' => 'GET', 'path' => 'mitra/kategori/{kategori}', 'desc' => 'Partners by category'],
                    ['method' => 'GET', 'path' => 'mitra/{id}', 'desc' => 'Partner detail by ID'],
                    ['method' => 'PUT', 'path' => 'mitra/{id}', 'desc' => 'Update partner data'],
                    ['method' => 'PATCH', 'path' => 'mitra/{id}/toggle-status', 'desc' => 'Enable / disable partner'],
                    ['method' => 'DELETE', 'path' => 'mitra/{id}', 'desc' => 'Delete partner along with its logo'],
                ],
            ],
            [
                'name' => 'Stakeholder',
                'prefix' => 'stakeholder',
                'color' => '#16336D',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'stakeholder', 'desc' => 'Display all stakeholder data'],
                    ['method' => 'POST', 'path' => 'stakeholder', 'desc' => 'Create a new stakeholder (upload logo)'],
                    ['method' => 'GET', 'path' => 'stakeholder/active', 'desc' => 'Stakeholders with active status'],
                    ['method' => 'PUT', 'path' => 'stakeholder/update-urutan', 'desc' => 'Update stakeholder display order'],
                    ['method' => 'GET', 'path' => 'stakeholder/{id}', 'desc' => 'Stakeholder detail by ID'],
                    ['method' => 'PUT', 'path' => 'stakeholder/{id}', 'desc' => 'Update stakeholder data'],
                    ['method' => 'PATCH', 'path' => 'stakeholder/{id}/toggle-status', 'desc' => 'Enable / disable stakeholder'],
                    ['method' => 'DELETE', 'path' => 'stakeholder/{id}', 'desc' => 'Delete stakeholder along with its logo'],
                ],
            ],
            [
                'name' => 'Program',
                'prefix' => 'program',
                'color' => '#97763A',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'program', 'desc' => 'Display all program data'],
                    ['method' => 'POST', 'path' => 'program', 'desc' => 'Create a new program (upload image)'],
                    ['method' => 'GET', 'path' => 'program/active', 'desc' => 'Programs with active status'],
                    ['method' => 'PUT', 'path' => 'program/update-urutan', 'desc' => 'Update program display order'],
                    ['method' => 'GET', 'path' => 'program/{id}', 'desc' => 'Program detail by ID'],
                    ['method' => 'PUT', 'path' => 'program/{id}', 'desc' => 'Update program data'],
                    ['method' => 'PATCH', 'path' => 'program/{id}/toggle-status', 'desc' => 'Enable / disable program'],
                    ['method' => 'DELETE', 'path' => 'program/{id}', 'desc' => 'Delete program along with its image'],
                ],
            ],
            [
                'name' => 'Projects',
                'prefix' => 'proyek',
                'color' => '#B09861',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'proyek', 'desc' => 'Display all project data'],
                    ['method' => 'POST', 'path' => 'proyek', 'desc' => 'Create a new project (upload thumbnail)'],
                    ['method' => 'GET', 'path' => 'proyek/active', 'desc' => 'Projects with active status'],
                    ['method' => 'PUT', 'path' => 'proyek/update-urutan', 'desc' => 'Update project display order'],
                    ['method' => 'GET', 'path' => 'proyek/slug/{slug}', 'desc' => 'Projects by slug'],
                    ['method' => 'GET', 'path' => 'proyek/status/{status}', 'desc' => 'Projects by status (draft/published/archived)'],
                    ['method' => 'GET', 'path' => 'proyek/kategori/{kategori}', 'desc' => 'Projects by category'],
                    ['method' => 'GET', 'path' => 'proyek/{id}', 'desc' => 'Project detail by ID'],
                    ['method' => 'PUT', 'path' => 'proyek/{id}', 'desc' => 'Update project data'],
                    ['method' => 'PATCH', 'path' => 'proyek/{id}/toggle-status', 'desc' => 'Enable / disable project'],
                    ['method' => 'DELETE', 'path' => 'proyek/{id}', 'desc' => 'Delete project along with its image'],
                ],
            ],
            [
                'name' => 'Project Gallery',
                'prefix' => 'proyek-galeri',
                'color' => '#5876B0',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'proyek-galeri', 'desc' => 'Display all project gallery'],
                    ['method' => 'POST', 'path' => 'proyek-galeri', 'desc' => 'Add project gallery photo'],
                    ['method' => 'GET', 'path' => 'proyek-galeri/proyek/{proyekId}', 'desc' => 'Gallery by project ID'],
                    ['method' => 'GET', 'path' => 'proyek-galeri/{id}', 'desc' => 'Gallery photo detail by ID'],
                    ['method' => 'PUT', 'path' => 'proyek-galeri/{id}', 'desc' => 'Update gallery photo'],
                    ['method' => 'PATCH', 'path' => 'proyek-galeri/{id}/toggle-status', 'desc' => 'Enable / disable gallery photo'],
                    ['method' => 'DELETE', 'path' => 'proyek-galeri/{id}', 'desc' => 'Delete gallery photo along with its file'],
                ],
            ],
            [
                'name' => 'News Categories',
                'prefix' => 'kategori-berita',
                'color' => '#7A2E3D',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'kategori-berita', 'desc' => 'Display all news categories with translations'],
                    ['method' => 'POST', 'path' => 'kategori-berita', 'desc' => 'Create a new news category'],
                    ['method' => 'GET', 'path' => 'kategori-berita/{id}', 'desc' => 'News category detail by ID'],
                    ['method' => 'PUT', 'path' => 'kategori-berita/{id}', 'desc' => 'Update news category'],
                    ['method' => 'DELETE', 'path' => 'kategori-berita/{id}', 'desc' => 'Delete news category'],
                ],
            ],
            [
                'name' => 'News',
                'prefix' => 'berita',
                'color' => '#A85C66',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'berita', 'desc' => 'Display all news data (including tags and translations)'],
                    ['method' => 'POST', 'path' => 'berita', 'desc' => 'Create a new article (upload image: gambar_utama, tag_ids)'],
                    ['method' => 'GET', 'path' => 'berita/active', 'desc' => 'News with active status (published)'],
                    ['method' => 'GET', 'path' => 'berita/slug/{slug}', 'desc' => 'News detail by slug with gallery and tags'],
                    ['method' => 'GET', 'path' => 'berita/status/{status}', 'desc' => 'News by status (draft/published/archived)'],
                    ['method' => 'GET', 'path' => 'berita/kategori/{kategori}', 'desc' => 'News by category'],
                    ['method' => 'GET', 'path' => 'berita/latest', 'desc' => 'Latest news (default limit 5)'],
                    ['method' => 'GET', 'path' => 'berita/{id}', 'desc' => 'News detail by ID'],
                    ['method' => 'PUT', 'path' => 'berita/{id}', 'desc' => 'Update news data'],
                    ['method' => 'PATCH', 'path' => 'berita/{id}/toggle-status', 'desc' => 'Enable / disable news'],
                    ['method' => 'DELETE', 'path' => 'berita/{id}', 'desc' => 'Delete news along with its image'],
                ],
            ],
            [
                'name' => 'News Tags',
                'prefix' => 'tag',
                'color' => '#9B4553',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'tag', 'desc' => 'Display all tags / news topics'],
                    ['method' => 'POST', 'path' => 'tag', 'desc' => 'Create a new tag'],
                    ['method' => 'GET', 'path' => 'tag/{id}', 'desc' => 'Tag detail by ID'],
                    ['method' => 'PUT', 'path' => 'tag/{id}', 'desc' => 'Update tag data'],
                    ['method' => 'PATCH', 'path' => 'tag/{id}/toggle-status', 'desc' => 'Enable / disable tag'],
                    ['method' => 'DELETE', 'path' => 'tag/{id}', 'desc' => 'Delete tag'],
                ],
            ],
            [
                'name' => 'News Gallery',
                'prefix' => 'berita-galeri',
                'color' => '#CC707C',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'berita-galeri', 'desc' => 'Display all news gallery'],
                    ['method' => 'POST', 'path' => 'berita-galeri', 'desc' => 'Add news gallery photo'],
                    ['method' => 'GET', 'path' => 'berita-galeri/berita/{beritaId}', 'desc' => 'Gallery by news ID'],
                    ['method' => 'GET', 'path' => 'berita-galeri/{id}', 'desc' => 'Detail foto galeri berdasarkan ID'],
                    ['method' => 'PUT', 'path' => 'berita-galeri/{id}', 'desc' => 'Update gallery photo'],
                    ['method' => 'PATCH', 'path' => 'berita-galeri/{id}/toggle-status', 'desc' => 'Enable / disable gallery photo'],
                    ['method' => 'DELETE', 'path' => 'berita-galeri/{id}', 'desc' => 'Delete gallery photo along with its file'],
                ],
            ],
            [
                'name' => 'Organizational Structure',
                'prefix' => 'struktur',
                'color' => '#8C4254',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'struktur', 'desc' => 'Display all organizational structures'],
                    ['method' => 'POST', 'path' => 'struktur', 'desc' => 'Create a new organizational structure (upload photo)'],
                    ['method' => 'GET', 'path' => 'struktur/active', 'desc' => 'Organizational structures with active status'],
                    ['method' => 'PUT', 'path' => 'struktur/update-urutan', 'desc' => 'Update structure display order'],
                    ['method' => 'GET', 'path' => 'struktur/{id}', 'desc' => 'Organizational structure detail by ID'],
                    ['method' => 'PUT', 'path' => 'struktur/{id}', 'desc' => 'Update organizational structure data'],
                    ['method' => 'PATCH', 'path' => 'struktur/{id}/toggle-status', 'desc' => 'Enable / disable structure'],
                    ['method' => 'DELETE', 'path' => 'struktur/{id}', 'desc' => 'Delete organizational structure along with its photo'],
                ],
            ],
            [
                'name' => 'Contacts',
                'prefix' => 'kontak',
                'color' => '#520A18',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'kontak', 'desc' => 'Display all contact data'],
                    ['method' => 'POST', 'path' => 'kontak', 'desc' => 'Create new contact data'],
                    ['method' => 'GET', 'path' => 'kontak/active', 'desc' => 'Contact data with active status'],
                    ['method' => 'GET', 'path' => 'kontak/{id}', 'desc' => 'Contact detail by ID'],
                    ['method' => 'PUT', 'path' => 'kontak/{id}', 'desc' => 'Update contact data'],
                    ['method' => 'PATCH', 'path' => 'kontak/{id}/toggle-status', 'desc' => 'Enable / disable contact'],
                    ['method' => 'DELETE', 'path' => 'kontak/{id}', 'desc' => 'Delete contact data'],
                ],
            ],
            [
                'name' => 'Contact Messages (Contact Form)',
                'prefix' => 'kontak-form',
                'color' => '#132C5C',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'kontak-form', 'desc' => 'Display all incoming messages'],
                    ['method' => 'POST', 'path' => 'kontak-form', 'desc' => 'Send a new contact message (public form)'],
                    ['method' => 'GET', 'path' => 'kontak-form/unread', 'desc' => 'Unread messages'],
                    ['method' => 'GET', 'path' => 'kontak-form/status/{status}', 'desc' => 'Messages by status (new/read/replied/spam)'],
                    ['method' => 'GET', 'path' => 'kontak-form/{id}', 'desc' => 'Message detail by ID'],
                    ['method' => 'PATCH', 'path' => 'kontak-form/{id}/status', 'desc' => 'Update message status (body: status)'],
                    ['method' => 'PATCH', 'path' => 'kontak-form/{id}/mark-read', 'desc' => 'Mark message as read'],
                    ['method' => 'PATCH', 'path' => 'kontak-form/{id}/mark-unread', 'desc' => 'Mark message as unread'],
                    ['method' => 'DELETE', 'path' => 'kontak-form/{id}', 'desc' => 'Delete contact message'],
                ],
            ],
            [
                'name' => 'Menu',
                'prefix' => 'menu',
                'color' => '#97763A',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'menu', 'desc' => 'Display all navigation menus'],
                    ['method' => 'POST', 'path' => 'menu', 'desc' => 'Create a new navigation menu'],
                    ['method' => 'GET', 'path' => 'menu/active', 'desc' => 'Menus with active status'],
                    ['method' => 'PUT', 'path' => 'menu/update-urutan', 'desc' => 'Update menu display order'],
                    ['method' => 'GET', 'path' => 'menu/slug/{slug}', 'desc' => 'Menu by slug'],
                    ['method' => 'GET', 'path' => 'menu/{id}', 'desc' => 'Menu detail by ID'],
                    ['method' => 'PUT', 'path' => 'menu/{id}', 'desc' => 'Update menu data'],
                    ['method' => 'PATCH', 'path' => 'menu/{id}/toggle-status', 'desc' => 'Enable / disable menu'],
                    ['method' => 'DELETE', 'path' => 'menu/{id}', 'desc' => 'Delete navigation menu'],
                ],
            ],
            [
                'name' => 'Footer',
                'prefix' => 'footer',
                'color' => '#2B4E94',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'footer', 'desc' => 'Display all footer links'],
                    ['method' => 'POST', 'path' => 'footer', 'desc' => 'Create a new footer link'],
                    ['method' => 'GET', 'path' => 'footer/active', 'desc' => 'Footer links with active status'],
                    ['method' => 'PUT', 'path' => 'footer/update-urutan', 'desc' => 'Update footer link display order'],
                    ['method' => 'GET', 'path' => 'footer/section/{section}', 'desc' => 'Footer by section'],
                    ['method' => 'GET', 'path' => 'footer/{id}', 'desc' => 'Footer detail by ID'],
                    ['method' => 'PUT', 'path' => 'footer/{id}', 'desc' => 'Update footer data'],
                    ['method' => 'PATCH', 'path' => 'footer/{id}/toggle-status', 'desc' => 'Enable / disable footer'],
                    ['method' => 'DELETE', 'path' => 'footer/{id}', 'desc' => 'Delete footer link'],
                ],
            ],
            [
                'name' => 'Language',
                'prefix' => 'bahasa',
                'color' => '#A85C66',
                'endpoints' => [
                    ['method' => 'GET', 'path' => 'bahasa', 'desc' => 'Display all registered languages'],
                    ['method' => 'POST', 'path' => 'bahasa', 'desc' => 'Add a new language (unique code 2-5 characters)'],
                    ['method' => 'GET', 'path' => 'bahasa/settings', 'desc' => 'Default language and list of currently active languages'],
                    ['method' => 'GET', 'path' => 'bahasa/available', 'desc' => 'List of active languages'],
                    ['method' => 'POST', 'path' => 'bahasa/switch/{locale}', 'desc' => 'Switch active session language'],
                    ['method' => 'GET', 'path' => 'bahasa/{kode}', 'desc' => 'Language detail by code'],
                    ['method' => 'PUT', 'path' => 'bahasa/{kode}', 'desc' => 'Update language data'],
                    ['method' => 'PATCH', 'path' => 'bahasa/{kode}/set-default', 'desc' => 'Set language as default'],
                    ['method' => 'PATCH', 'path' => 'bahasa/{kode}/toggle-status', 'desc' => 'Enable / disable language'],
                    ['method' => 'DELETE', 'path' => 'bahasa/{kode}', 'desc' => 'Delete language along with all its translations'],
                ],
            ],
        ];
    }
}
